server:
  port: 9192
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: order-service
logging:
  file: C:/Users/Basant.Hota/Desktop/oms.log

